### ISSUE TITLE
Json output has no (meaningful) content... Just look at the difference between the XML and the feed parsed from.the Python script

### ISSUE THREAD

**Issue by s3r1alpari4h** [RiiConnect24/RiiConnect24-File-Maker#1]
XML itself:

~ # curl http://feeds.bbci.co.uk/news/technology/rss.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet title="XSL_formatting" type="text/xsl" href="/shared/bsp/xsl/rss/nolsol.xsl"?>

<rss xmlns:media="http://search.yahoo.com/mrss/" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
  <channel>
    <title>BBC News - Technology</title>
    <link>http://www.bbc.co.uk/news/technology/#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
    <description>The latest stories from the Technology section of the BBC News web site.</description>
    <language>en-gb</language>
    <lastBuildDate>Tue, 29 Sep 2015 19:21:19 GMT</lastBuildDate>
    <copyright>Copyright: (C) British Broadcasting Corporation, see http://news.bbc.co.uk/2/hi/help/rss/4498287.stm for terms and conditions of reuse.</copyright>
    <image>
      <url>http://news.bbcimg.co.uk/nol/shared/img/bbc_news_120x60.gif</url>
      <title>BBC News - Technology</title>
      <link>http://www.bbc.co.uk/news/technology/#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <width>120</width>
      <height>60</height>
    </image>
    <ttl>15</ttl>
    <atom:link href="http://feeds.bbci.co.uk/news/technology/rss.xml" rel="self" type="application/rss+xml"/>
    <item>
      <title>Google adds wi-fi to old hi-fis</title>
      <description>Google unveils a budget-priced accessory that lets old hi-fis and other speaker systems stream audio over wi-fi.</description>
      <link>http://www.bbc.co.uk/news/technology-34391038#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34391038</guid>
      <pubDate>Tue, 29 Sep 2015 17:03:56 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/C79E/production/_85820115_85817118.jpg"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/EEAE/production/_85820116_85817118.jpg"/>
    </item>
    <item>
      <title>Medical devices attract hackers</title>
      <description>Researchers have found evidence that thousands of critical medical machines, such as MRI scanners, are available to access online.</description>
      <link>http://www.bbc.co.uk/news/technology-34390165#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34390165</guid>
      <pubDate>Tue, 29 Sep 2015 12:55:05 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/A6E1/production/_85812724_mriscanner.gif"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/CDF1/production/_85812725_mriscanner.gif"/>
    </item>
    <item>
      <title>Facebook reacts to hoax privacy posts</title>
      <description>The social network has hit back at the latest round of rumours about privacy settings with a light-hearted reassurance to its Earth-bound users.</description>
      <link>http://www.bbc.co.uk/news/technology-34393666#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34393666</guid>
      <pubDate>Tue, 29 Sep 2015 14:08:20 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/17C3D/production/_85814379_mars2.gif"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/2095/production/_85814380_mars2.gif"/>
    </item>
    <item>
      <title>Snowden launches Twitter account</title>
      <description>Fugitive US intelligence contractor Edward Snowden opens an account on the social network website Twitter, following one other user - the NSA.</description>
      <link>http://www.bbc.co.uk/news/world-us-canada-34395919#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/world-us-canada-34395919</guid>
      <pubDate>Tue, 29 Sep 2015 17:49:17 GMT</pubDate>
    </item>
    <item>
      <title>London taxi rules would 'end Uber'</title>
      <description>Uber says a consultation on private hire regulation could spell an end to the way the taxi-hailing app operates.</description>
      <link>http://www.bbc.co.uk/news/uk-england-london-34394774#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/uk-england-london-34394774</guid>
      <pubDate>Tue, 29 Sep 2015 18:37:15 GMT</pubDate>
    </item>
    <item>
      <title>Tinder fights STD ad campaign in US</title>
      <description>Tinder is calling for the removal of an advertising campaign by an Aids awareness group, which linked the dating app with sexually transmitted diseases.</description>
      <link>http://www.bbc.co.uk/news/technology-34390795#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34390795</guid>
      <pubDate>Tue, 29 Sep 2015 10:52:41 GMT</pubDate>
    </item>
    <item>
      <title>Google chief on search's new frontier</title>
      <description>Google's search chief explains how Now on Tap furthers his firm's goal of being able to deliver results without asking users to type in requests.</description>
      <link>http://www.bbc.co.uk/news/technology-34351458#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34351458</guid>
      <pubDate>Mon, 28 Sep 2015 23:01:08 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/17598/production/_85804659_85804652.jpg"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/19F0/production/_85804660_85804652.jpg"/>
    </item>
    <item>
      <title>Russian crackdown on pirated music</title>
      <description>Widely used Russian social network VKontakte must use "effective technology" to end pirated music on its site.</description>
      <link>http://www.bbc.co.uk/news/technology-34390166#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34390166</guid>
      <pubDate>Tue, 29 Sep 2015 11:02:30 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/101BC/production/_85808956_vk.gif"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/128CC/production/_85808957_vk.gif"/>
    </item>
    <item>
      <title>Chinese smartphones mount web attack</title>
      <description>More than 650,000 Chinese smartphones have been unwittingly enrolled in a massive attack that overwhelmed a web server.</description>
      <link>http://www.bbc.co.uk/news/technology-34379254#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34379254</guid>
      <pubDate>Mon, 28 Sep 2015 10:21:41 GMT</pubDate>
    </item>
    <item>
      <title>Hilton investigates hack claims</title>
      <description>The Hilton hotel group says it is investigating claims its US shops and gift stores may be the source of a credit-card hack.</description>
      <link>http://www.bbc.co.uk/news/technology-34379624#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34379624</guid>
      <pubDate>Mon, 28 Sep 2015 09:59:30 GMT</pubDate>
    </item>
    <item>
      <title>Facebook down for second time in week</title>
      <description>A 40-minute outage on Facebook was the second time in a week the popular site went down, and was followed by a shares tumble.</description>        <link>http://www.bbc.co.uk/news/world-us-canada-34383655#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/world-us-canada-34383655</guid>
      <pubDate>Mon, 28 Sep 2015 22:59:39 GMT</pubDate>
    </item>
    <item>
      <title>Android 'privacy' phone revamped</title>
      <description>Security firm Silent Circle has revamped its own-brand smartphone that helps people manage data they share with apps</description>
      <link>http://www.bbc.co.uk/news/technology-34346805#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34346805</guid>
      <pubDate>Mon, 28 Sep 2015 07:13:51 GMT</pubDate>
    </item>
    <item>
      <title>Brain reader helps man move legs again</title>
      <description>A paralysed man has been able to regain some control over his legs using a device to read his brain, scientists say.</description>
      <link>http://www.bbc.co.uk/news/health-34335514#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/health-34335514</guid>
      <pubDate>Thu, 24 Sep 2015 01:17:46 GMT</pubDate>
    </item>
    <item>
      <title>VIDEO: New scan aims to aid tumour detection</title>
      <description>Microsoft Research is working on software that could measure tumours 40 times quicker than current methods.</description>
      <link>http://www.bbc.co.uk/news/technology-34210351#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34210351</guid>
      <pubDate>Tue, 22 Sep 2015 23:39:46 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/2C7D/production/_85698311_de27.jpg"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/538D/production/_85698312_de27.jpg"/>
    </item>
    <item>
      <title>VIDEO: The lens that could shrink your camera</title>
      <description>Engineers at the California Institute of Technology are working on creating super-thin lenses.</description>
      <link>http://www.bbc.co.uk/news/technology-34210347#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34210347</guid>
      <pubDate>Mon, 21 Sep 2015 07:52:40 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/16FC8/production/_85625149_de27.jpg"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/1420/production/_85625150_de27.jpg"/>
    </item>
    <item>
      <title>VIDEO: The simulator bringing movement to VR</title>
      <description>The simulator which aims to bring the physical sensations of movement to virtual reality</description>
      <link>http://www.bbc.co.uk/news/technology-34251099#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34251099</guid>
      <pubDate>Tue, 29 Sep 2015 23:04:36 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/6E15/production/_85818182_vr_simulator1920.jpg"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/9525/production/_85818183_vr_simulator1920.jpg"/>
    </item>
    <item>
      <title>VIDEO: Could AI make drugs to treat cancer?</title>
      <description>How artificial intelligence could be used to test thousands of drug combinations to treat medical conditions</description>
      <link>http://www.bbc.co.uk/news/technology-34326577#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34326577</guid>
      <pubDate>Tue, 29 Sep 2015 08:38:50 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/07E3/production/_85691020_drug_capsules_afp.jpg"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/2EF3/production/_85691021_drug_capsules_afp.jpg"/>
    </item>
    <item>
      <title>VIDEO: Bad content will 'destroy' VR industry</title>
      <description>Emmy winning company Secret Location speak to BBC Click about the future of virtual reality</description>
      <link>http://www.bbc.co.uk/news/technology-34251095#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34251095</guid>
      <pubDate>Mon, 28 Sep 2015 07:19:09 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/9489/production/_85752083_de27.jpg"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/BB99/production/_85752084_de27.jpg"/>
    </item>
    <item>
      <title>VIDEO: Blackphone 2 aims to protect privacy</title>
      <description>The maker of a second-generation Android smartphone that promises to protect its users' privacy explain how it works.</description>
      <link>http://www.bbc.co.uk/news/technology-34349620#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34349620</guid>
      <pubDate>Mon, 28 Sep 2015 07:14:59 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/2AE6/production/_85728901_phone2.jpg"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/51F6/production/_85728902_phone2.jpg"/>
    </item>
    <item>
      <title>VIDEO: Why is Modi so interested in Facebook?</title>
      <description>Why is Indian Prime Minister Narendra Modi so keen to court Facebook?</description>
      <link>http://www.bbc.co.uk/news/business-34376827#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/business-34376827</guid>
      <pubDate>Mon, 28 Sep 2015 01:54:01 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/9DF6/production/_85783404_a2c3d985-a616-4897-9c24-fae1d35497f5.jpg"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/C506/production/_85783405_a2c3d985-a616-4897-9c24-fae1d35497f5.jpg"/>
    </item>
    <item>
      <title>VIDEO: See the telescopes of the future</title>
      <description>As India launches its first space telescope, BBC News looks at some of the innovations getting astronomers excited.</description>
      <link>http://www.bbc.co.uk/news/science-environment-34358738#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/science-environment-34358738</guid>
      <pubDate>Sun, 27 Sep 2015 23:04:25 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/336D/production/_85756131_85755757.jpg"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/5A7D/production/_85756132_85755757.jpg"/>
    </item>
    <item>
      <title>VIDEO: Bill Gates: Meeting poverty goals 'won't be easy'</title>
      <description>Microsoft founder Bill Gates and his wife Melinda have spoken to the BBC's James Robbins about their hopes for beating poverty and malnutrition and improving childhood health.</description>
      <link>http://www.bbc.co.uk/news/world-us-canada-34372572#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/world-us-canada-34372572</guid>
      <pubDate>Sun, 27 Sep 2015 04:20:31 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/3801/production/_85773341_85773323.jpg"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/5F11/production/_85773342_85773323.jpg"/>
    </item>
    <item>
      <title>VIDEO: Kit helps children hunt new antibiotics</title>
      <description>Designer and entrepreneur Vidhi Mehta has developed a biology kit that helps children become ''citizen scientists'', hunting new antibiotics.</description>
      <link>http://www.bbc.co.uk/news/science-environment-34337993#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/science-environment-34337993</guid>
      <pubDate>Sat, 26 Sep 2015 23:14:17 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/171D0/production/_85727649_img_0760.jpg"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/1628/production/_85727650_img_0760.jpg"/>
    </item>
    <item>
      <title>Is your home about to get a lot smarter?</title>
      <description>How wi-fi enabled gadgets are making your property smarter</description>
      <link>http://www.bbc.co.uk/news/business-34378047#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/business-34378047</guid>
      <pubDate>Mon, 28 Sep 2015 23:00:37 GMT</pubDate>
    </item>
    <item>
      <title>How to stop Apple Music auto-subscription</title>
      <description>How to stop Apple Music auto-subscription</description>
      <link>http://www.bbc.co.uk/newsbeat/34388030#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/newsbeat/34388030</guid>
      <pubDate>Tue, 29 Sep 2015 07:13:29 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/A23A/production/_85803514_turnoffwarning.jpg"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/D17E/production/_85803635_turnoffwarning.jpg"/>
    </item>
    <item>
      <title>Silicon Valley - still the capital of tech</title>
      <description>What makes Silicon Valley tick?</description>
      <link>http://www.bbc.co.uk/news/technology-34357044#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/technology-34357044</guid>
      <pubDate>Fri, 25 Sep 2015 08:58:42 GMT</pubDate>
    </item>
    <item>
      <title>How to get a job in gaming</title>
      <description>A games industry veteran's top tips for getting into gaming</description>
      <link>http://www.bbc.co.uk/newsbeat/34360540#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/newsbeat/34360540</guid>
      <pubDate>Fri, 25 Sep 2015 15:33:25 GMT</pubDate>
      <media:thumbnail width="66" height="49" url="http://c.files.bbci.co.uk/14FC3/production/_85755958_img_5531.jpg"/>
      <media:thumbnail width="144" height="81" url="http://c.files.bbci.co.uk/176D3/production/_85755959_img_5531.jpg"/>
    </item>
    <item>
      <title>How events are becoming digital playgrounds</title>
      <description>Why event organising is a hidden industry</description>
      <link>http://www.bbc.co.uk/news/business-34335055#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/business-34335055</guid>
      <pubDate>Fri, 25 Sep 2015 02:00:08 GMT</pubDate>
    </item>
    <item>
      <title>Want superfast broadband? Do it yourself</title>
      <description>How DIY superfast broadband is speeding up the countryside</description>
      <link>http://www.bbc.co.uk/news/business-34256790#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa</link>
      <guid isPermaLink="false">http://www.bbc.co.uk/news/business-34256790</guid>
      <pubDate>Mon, 21 Sep 2015 23:01:02 GMT</pubDate>
    </item>
  </channel>
</rss>

Output from script: (tech only)

{'updated': u'Tue, 29 Sep 2015 19:21:19 GMT', 'subtitle': u'The latest stories from the Technology section of the BBC News web site.', 'language': u'en-gb', 'links': [{'href': u'http://www.bbc.co.uk/news/technology/#sa-ns_mchannel=rss&ns_source=PublicRSS20-sa', 'type': u'text/html', 'rel': u'alternate'}, {'href': u'http://feeds.bbci.co.uk/news/technology/rss.xml', 'type': u'application/rss+xml', 'rel': u'self'}], 'title': u'BBC News - Technology', 'image': {'links': [{'href': u'http://www.bbc.co.uk/news/technology/#sa-ns_mchannel=rss&ns_source=PublicRSS20-sa', 'type': u'text/html', 'rel': u'alternate'}], 'title': u'BBC News - Technology', 'height': 60, 'width': 120, 'title_detail': {'base': u'http://feeds.bbci.co.uk/news/technology/rss.xml', 'type': u'text/plain', 'value': u'BBC News - Technology', 'language': None}, 'href': u'http://news.bbcimg.co.uk/nol/shared/img/bbc_news_120x60.gif', 'link': u'http://www.bbc.co.uk/news/technology/#sa-ns_mchannel=rss&ns_source=PublicRSS20-sa'}, 'rights': u'Copyright: (C) British Broadcasting Corporation, see http://news.bbc.co.uk/2/hi/help/rss/4498287.stm for terms and conditions of reuse.', 'subtitle_detail': {'base': u'http://feeds.bbci.co.uk/news/technology/rss.xml', 'type': u'text/html', 'value': u'The latest stories from the Technology section of the BBC News web site.', 'language': None}, 'title_detail': {'base': u'http://feeds.bbci.co.uk/news/technology/rss.xml', 'type': u'text/plain', 'value': u'BBC News - Technology', 'language': None}, 'link': u'http://www.bbc.co.uk/news/technology/#sa-ns_mchannel=rss&ns_source=PublicRSS20-sa', 'ttl': u'15', 'rights_detail': {'base': u'http://feeds.bbci.co.uk/news/technology/rss.xml', 'type': u'text/plain', 'value': u'Copyright: (C) British Broadcasting Corporation, see http://news.bbc.co.uk/2/hi/help/rss/4498287.stm for terms and conditions of reuse.', 'language': None}, 'updated_parsed': time.struct_time(tm_year=2015, tm_mon=9, tm_mday=29, tm_hour=19, tm_min=21, tm_sec=19, tm_wday=1, tm_yday=272, tm_isdst=0)}

**Comment by s3r1alpari4h** [comment]
BTW I should've mentioned this is for news

**Comment by s3r1alpari4h** [comment]
Also that isn't the raw output of curl. Github seems to apply html tags so they are applied.

**Comment by larsenv** [comment]
Thanks, the problem was that it was accepting the first node I supplied. I'll have to find the correct syntax to do so, [1] doesn't seem to work with Universal Feed Parser.
